input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [level] {
    mutate {
      rename => { "level" => "severity" }
    }
  }
  if [message] {
    mutate {
      strip => ["message"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "ditto-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
