name: "Publish Container Image"

on:
  workflow_dispatch:

permissions:
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      packages: write

    steps:
      - name: Clean up old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_workflow_pattern: ${{ github.workflow }}

      - name: Checkout code
        uses: actions/checkout@main

      - name: Set lowercase image name
        run: |
          CONTAINER_NAME="${{ github.event.repository.name }}"
          echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
          LOWER_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "LOWER_NAME=$LOWER_NAME" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          file: server/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_NAME }}:latest

      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.CONTAINER_NAME }}
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: "true"